apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-lab-deployment
  labels:
    app: kube-lab-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-lab-app
  template:
    metadata:
      labels:
        app:  kube-lab-app # error introduced here
    spec:
      containers:
      - name: kube-lab-container
        image: kube-lab-app:v100
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"