apiVersion: v1
kind: Service
metadata:
  name: kube-lab-service
spec:
  selector:
    app: kube-lab-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000 
  # NodePort type exposes the Service externally
  type: LoadBalancer