apiVersion: v1
kind: Service
metadata:
  name: kube-lab-service
spec:
  # The 'selector' links this Service to the Pods with the 'app: kube-lab-app' label
  selector:
    app: kube-lab-app
  ports:
    # Port 80 is the port the Service exposes
    - protocol: TCP
      port: 80
      # TargetPort 8080 is the port the container is listening on
      targetPort: 8080
      # NodePort is the port on your host machine that exposes the service
      nodePort: 30000 
  # NodePort type exposes the Service externally
  type: NodePort